language: python
sudo: required
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  
  # install the package
  - python3 setup.py install
  - python3 -m pip install `python3 setup.py requirements`
  
  # show the versions
  - py.test --version
  - python3 setup.py requirements

script:
  
  # test with pep8
  # add coverage for python 3.3 and above
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then py.test knittingpattern --pep8; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then py.test knittingpattern --cov=knittingpattern --pep8; fi
  
  # test import form everywhere
  - ( cd / && python3 -c "import knittingpattern;print(\"imported\")" )
  
  # run tests from installation
  - ( cd / && py.test --pyargs knittingpattern )
  
after_script:

  # https://github.com/codeclimate/python-test-reporter
  # set the environment variable CODECLIMATE_REPO_TOKEN in travis-ci settings
  - codeclimate-test-reporter
